Fix iOS crash with missing fallback
```
RCTFatalException: Exception '-[__NSCFBoolean value]: unrecognized selector sent to instance 0x25e9bda00' was thrown while in...:
```